### ISSUE TITLE
[Bug]: right side elements apper

### ISSUE THREAD

**Issue by EmanuelLopesS2** [cominixo/BetterF3#57]
### Describe the Bug

I deleted all the right side elements from the F3 screen and put some of them is the left side, but after restarting the game ALL the right side elements  are shown again, but those in the left side still the same as i left before.
I don't know if the same happens if I did the same with the left side, but it's boring to delete all the elements every time I start the game

### Steps to Reproduce

Just delete all the right side elements and restart the game

### Expected Behavior

Still the same as I left before

### Screenshots

Before restarting the game:
![Screenshot_1](https://user-images.githubusercontent.com/38889284/146761612-fafaa25f-efa3-4f57-aee0-5b5725294d22.png)

After Restarting the game:
![image](https://user-images.githubusercontent.com/38889284/146761842-c995a2c4-9275-4c28-b74c-c9c7bbe9a794.png)

### Modloader Type

Minecraft Forge

### Modloader Version

Forge 39.0.5

### Mod Version

1.2.2

**Comment by CWO333** [comment]
The issue could happen on either side. It's because if you set either side to have nothing, when the mod loads that side (it loads left and right independently), it sees the config as empty and loads the defaults. A workaround for now is to leave a Separator in the side you want empty so it's not entirely empty but doesn't show anything.
